### ISSUE TITLE
Submitting job to HealthScribe fails with status code 400

### ISSUE THREAD

**Issue by speriosu** [aws-samples/aws-healthscribe-demo#11]
<img width="568" alt="image" src="https://github.com/aws-samples/aws-healthscribe-demo/assets/282688/4234775b-bbe4-482b-bf47-4607ba1a9246">

Hi, deploying the demo app with Amplify worked great, but when I go to actually submit a job to create a conversation, I consistently get this error message with a status code of 400. This happens whether I use one of the built-in mock templates or my own generated audio from a very simplified transcript.

Here's what the form looks like before I submit and see the error:

<img width="798" alt="image" src="https://github.com/aws-samples/aws-healthscribe-demo/assets/282688/62d650a5-b8c8-4299-8715-5059e60a28fb">

There are only 2 speakers in the audio, and they are not separated by channel. (They come straight out of the app's own audio generator.)

How should I troubleshoot this?

**Comment by yyao84** [comment]
Hi @speriosu, this is an error calling the HealthScribe API, and the error message should be returned on that API call.

To get the error message,

- open your browser's debug console before submitting a job
- select the network tab
- submit the job
- you should see several calls to S3 while your audio files are uploaded, and a `POST` call to `https://transcribe.us-east-1.amazonaws.com/`, to invoke the HealthScribe API
- select this call in the debug console
- select the `Response` tab - the error message will be there

We can work on identifying the fix once the error message is known.

**Comment by Yageen95** [comment]
I am experiencing the same issue. The response I am getting is:

{"__type":"BadRequestException","Message":"Your account isn't authorized to call this operation. Check your account permissions and try your request again."}

I reviewed and edited the permissions and roles for the Cognito group, making sure they covered all actions and resources. But still, the error persists. Is there any specific action or additional configuration I might be missing to resolve this authorization issue?

**Comment by yyao84** [comment]
Hi @Yageen95 - I was able to reproduce the error message by calling HealthScribe (transcribe API) in a region other than `us-east-1`.  

From the browser network monitor, can you confirm the `POST` call is made to `us-east-1`? The URL is `https://transcribe.us-easat-1.amazonaws.com`. If the region differs, you can reset the region setting:
1) Select `Settings`
2) Expand `Advanced`
3) Change the setting for `API Timing`
4) Select `Save`
5) Change the `API Timing` setting to the original, then select `Save` again

I tried other scenarios - adding a deny service control policy, restricting S3 by bucket policy, changing the trusted entity in the assume role, and deploying the app in a different region - the error messages from those were specific to the exact issue.

If the demo is calling the API in `us-east-1`, we can set up a troubleshooting session, if you're open to that.

**Comment by Yageen95** [comment]
Thanks so much @yyao84 - the issue was the region. I set up the application to run on us-east-2 not knowing Healthscribe is only available on us-east-1. Thanks!

**Comment by yyao84** [comment]
Great to hear @Yageen95 ! Closing this issue. 

@speriosu - please leave a comment if you're still experiencing the 400 error, and I'll reopen.
