### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by ken-sheppard** [aws-samples/aws-healthscribe-demo#22]
This PR 0fc71a51bdf6af6172ce6c5d80110a2752582a55 looks to have broken the build. The IEvidenceNew and IAuraClinicalDocOutputSectionNew might be missing. It fails locally and if I build in Amplify. If can build https://github.com/aws-samples/aws-healthscribe-demo/commit/838da88863a470995690c98ddf009959e81a4f8c in Amplify. I think the updated version of /src/types/HealthScribe.ts is missing.

**Comment by yyao84** [comment]
@ken-sheppard - apologies for the error. The 0fc71a5 update removed outdated data formats for clinical summarizations, but not all data types were renamed correctly (and I didn't do adequate testing). Please let me know if this new PR works for you. Thanks!

**Comment by yyao84** [comment]
@ken-sheppard the build hook is implemented. Please let me know if you run into any other issues.
