### ISSUE TITLE
file conversion transcription jsons to paragraphs

### ISSUE THREAD

**Issue by ankitklad** [aws-samples/aws-healthscribe-demo#28]
not able to see/find function or code that converts health scribe job output transcription jsons into readable texts(paragraph)

**Comment by yyao84** [comment]
Hi @ankitklad,

This [useEffect hook](https://github.com/aws-samples/aws-healthscribe-demo/blob/5edfd45e192ecd8f80868304195473b97c40a6a6/src/components/Conversation/LeftPanel/LeftPanel.tsx#L62-L158) does this in `LeftPanel`.

`transcriptMod` gives you an object of spoken text that you can parse into paragraphs:
```
[key: string (segmentId)]: {
  "BeginAudioTime": number,
  "Content": string,
  "EndAudioTime": number,
  "ParticipantDetails": {
    "ParticipantRole": "PATIENT_0" | "CLINICIAN_0" | "PATIENT_1" ... etc
  },
  "SectionDetails": {
    "SectionName": "SMALL_TALK" | "SUBJECTIVE" | "OBJECTIVE" | "ASSESSMENT_AND_PLAN" ...etc
  },
  "SegmentId": string (segmentId),
  "Words": [
    {
      "Alternatives": [
        {
          "Confidence": number,
          "Content": string,
        }
      ],
      "BeginAudioTime": number,
      "EndAudioTime": number,
      "Type": "PRONUNCIATION" | "PUNCTUATION"
    },
    ...
  ]
}
```

You can get an array of just the conversation with something like:
```
values(segmentDict).map((d) => `${d.ParticipantDetails.ParticipantRole}: ${d.Content}`)
```

**Comment by yyao84** [comment]
@ankitklad - please let me know if you have any additional questions

**Comment by ankitklad** [comment]
Hi Yuan,

Can you please share complete CloudFormation template for this.

Regards
Ankit Lad

**Comment by yyao84** [comment]
@ankitklad - this demo uses [AWS Amplify](https://aws.amazon.com/amplify/) to orchestrate the full-stack deployment. If you deploy this in your account, you'll be able to reference the CloudFormation templates this generates.

**Comment by ankitklad** [comment]
Thank you for your response.

But I am trying to run same templates but somehow I feel its not complete. I am trying to run it in my organization where we have to add boundary permissions to IAM role, still it keeps on throwing errors. I am using attached CloudFormation templates.

Additional I have replicated git into my own account and tried. But somehow that is also failing.
https://github.com/ankitklad/aws-healthscribe-demo

Regards
Ankit Lad

**Comment by yyao84** [comment]
To clarify your requirement - all deployed IAM roles must have a permissions boundary attached.  Is this correct? How are you correctly deploying this project?

**Comment by ankitklad** [comment]
That is correct. I have tried it in two ways.

  1.  Deployment of attached CloudFormation template
  2.  Updating IAM roles(with boundary permission) in Gitrepo -https://github.com/ankitklad/aws-healthscribe-demo and deploy it using Amplify.

But both are failing.

Regards
Ankit Lad

**Comment by ankitklad** [comment]
Hi Yuan,

Wanted to check if you had time to look into it?

Regards
Ankit Lad
From: Lad, Ankitkumar (Cognizant) ***@***.***>
Sent: Wednesday, July 3, 2024 10:37 AM
To: aws-samples/aws-healthscribe-demo ***@***.***>; aws-samples/aws-healthscribe-demo ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [aws-samples/aws-healthscribe-demo] file conversion transcription jsons to paragraphs (Issue #28)

That is correct. I have tried it in two ways.

  1.  Deployment of attached CloudFormation template
  2.  Updating IAM roles(with boundary permission) in Gitrepo -https://github.com/ankitklad/aws-healthscribe-demo and deploy it using Amplify.

But both are failing.

Regards
Ankit Lad

**Comment by yyao84** [comment]
Amplify [supports creating IAM roles with permissions boundaries](https://docs.amplify.aws/gen1/react/tools/cli/project/permissions-boundary/).

In this scenario, you create a permissions boundary policy, then use the Amplify CLI to apply it to the project. During deployment, all Amplify-created IAM roles will have the permissions boundary applied.

You will still need an IAM role for Amplify to assume in order to deploy the project. This role can have a permissions boundary but it needs things like iam:CreateRole, iam:PassRole, etc. 

Does this fit your requirements?
