### ISSUE TITLE
S3 bucket in wrong region error

### ISSUE THREAD

**Issue by ambihealth** [aws-samples/aws-healthscribe-demo#32]
Hi AWS team, cloned the repo into our private org and ran Amplify build which completed successfully. 

Audio gets successfully uploaded to US-East-2 bucket but then Healthscribe App gives an error that S3 bucket is not in correct region. 

Amplify config docs do not specify region when creating bucket. Can you help me understand why it's building S3 buckets in East-2 when application is in East-1? 

Thanks!

**Comment by yyao84** [comment]
Hi @ambihealth - the S3 bucket where audio is uploaded is in the same region where the Amplify application is deployed. Unfortunately the documentation and the Amplify deployment button does not specify `us-east-1`. We'll be updating this today. 

To resolve this issue you can delete the current demo Amplify application in `us-east-2`, and re-deploy it in the `us-east-1` region. The updated link will look like this: 
`https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/deploy?repo=https://github.com/aws-samples/aws-healthscribe-demo`

**Comment by ambihealth** [comment]
Thank you. That worked perfectly.
